name: floor_common
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.2.0
homepage: https://floor.codes
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  floor_annotation:
    path: ../floor_annotation/
  meta: ^1.7.0
  path: ^1.8.0
  sqflite_common: ^2.0.1+1

dev_dependencies:
  build_runner: ^2.1.2
  collection: ^1.15.0
  floor_generator:
    path: ../floor_generator/
  sqflite_common_ffi: ^2.0.0+3
  test: ^1.20.1
  matcher: ^0.12.10
  mockito: ^5.0.15
